Task7: Create upload/download files from Minio
Fulindak/warehouse pull request #11
Opened 2024-06-06 12:42 UTC by Fulindak

2024-06-15 09:38 UTC, GUR-ok commented
поправь конфликты плз

2024-06-15 09:44 UTC, GUR-ok requested changes

2024-06-15 09:44 UTC, GUR-ok commented on src/main/resources/db/changelog/v3.0.0/create-product-image-table.xml
> +            <column name="expansion" type="varchar(10)">
давай уберем expansion вообще. Можем имя файла, включая расширение, хранить в мета-дате файла в s3, minio?

2024-06-15 09:44 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public void uploadImg(@PathVariable UUID productId, @RequestParam("file") MultipartFile image) {
пусть возвращает айдишник файла

2024-06-15 09:44 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public void downloadImgs(@PathVariable UUID productId, HttpServletResponse response) {
Давай немного переделаем. 
1. Попробуем возвращать StreamingResponseBody. Чтоб не юзать HttpServletResponse response.
2. в аргумент сервисного метода передавать outputStream, только он возьмется из StreamingResponseBody, пример ниже:

Псевдокодный пример как передать outputStream в сервис
```
    @GetMapping("/foo")
    public StreamingResponseBody downloadZip() {
        StreamingResponseBody stream = out -> {
            вызовСервисаДляЗагрузкиАрхива(out);
        };
        
        return stream;
    }
```

2024-06-15 09:44 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public void downloadImgs(@PathVariable UUID productId, HttpServletResponse response) {
будет на самом деле ```ResponseEntity<StreamingResponseBody>```. нужно еще хедеры не забыть положить в ResponseEntity c content-disposition

2024-06-15 09:44 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/ProductService.java
> +        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, ContentDisposition.attachment()
хедеры тут приделывать не оч хорошо. давай их в контроллере.

2024-06-15 09:44 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/ProductService.java
> +    public void downloadImgs(UUID productId, HttpServletResponse response) {
тут принимать в аргументах не HttpServletResponse response, а outputStream

2024-06-27 09:50 UTC, Fulindak commented on src/main/resources/db/changelog/v3.0.0/create-product-image-table.xml
> +            <column name="expansion" type="varchar(10)">
исправил, разобрался с метадатой и закинул всю инфу туда

2024-06-27 09:50 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public void uploadImg(@PathVariable UUID productId, @RequestParam("file") MultipartFile image) {
исправил

2024-06-27 09:54 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public void downloadImgs(@PathVariable UUID productId, HttpServletResponse response) {
исправил

2024-06-27 09:54 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/ProductService.java
> +        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, ContentDisposition.attachment()
исправил

2024-06-27 09:54 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/ProductService.java
> +    public void downloadImgs(UUID productId, HttpServletResponse response) {
исправил

2024-07-03 10:18 UTC, merged