Task 2: create Criteria Api
Fulindak/warehouse pull request #4
Opened 2024-04-25 10:47 UTC by Fulindak

Сразу извиняюсь, что не успел написать тесты к все методом Service (не хватило времени из-за работы).

2024-04-27 07:17 UTC, GUR-ok requested changes

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public ResponseEntity<List<ProductResponse>> searchByCriteria(@Validated @RequestBody List<Criteria> criteriaList) {
где пагинация в запросе?

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +
лишние пустые строки. следи за форматированием плз

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/exceptions/ControllerAdvice.java
> +
тут тоже пустая строка не нужна

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/search/ProductSpecification.java
> +public class ProductSpecification {
Не нужно ее делать бином

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/search/ProductSpecification.java
> +public class ProductSpecification {
ее нужно заимплементить от библиотечной
```implements Specification<Product> {```

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/search/ProductSpecification.java
> +public class ProductSpecification {
```List<Predicate> predicates = new ArrayList<>();``` нужно хранить в прпоерти объекта нашей спецификации ProductSpecification и принмиать через конструктор

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/search/enums/Operation.java
> +    static {
Как-то усложнил с этими стастик мапами
Есть такие варианты:
```
public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```
или вообще так

```
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;

public enum OperationType {
    @JsonProperty("operation")
    @JsonAlias({"="})
    EQUAL,

    @JsonProperty("operation")
    @JsonAlias({">="})
    GRATER_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"<="})
    LESS_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"~"})
    LIKE;
}
```

2024-04-27 07:17 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/search/creteria/LocalDateCriteria.java
> +    private final PredicateStrategy<LocalDate> strategy = new LocalDateStrategy();
Давай сделаем статическим везде, чтобы не создавать каждый раз стратегию при создании криетрия.  @JsonIgnore можно будет убрать в интерфейсе

2024-04-28 14:46 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public ResponseEntity<List<ProductResponse>> searchByCriteria(@Validated @RequestBody List<Criteria> criteriaList) {
Исправил, теперь передается Pageable вместе с критериями

2024-04-28 14:57 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +
Теперь настроил идею,надеюсь не буду забывать нажимать Ctrl + Alt + L

2024-04-28 14:57 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/exceptions/ControllerAdvice.java
> +
Теперь настроил идею,надеюсь не буду забывать нажимать Ctrl + Alt + L

2024-04-28 14:58 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/search/enums/Operation.java
> +    static {
Что-то я и правда себя перемудрил, исправил

2024-04-28 14:58 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/search/creteria/LocalDateCriteria.java
> +    private final PredicateStrategy<LocalDate> strategy = new LocalDateStrategy();
Сделал

2024-04-29 09:02 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public ResponseEntity<List<ProductResponse>> searchByCriteria(@Validated @RequestBody List<Criteria> criteriaList) {
не могу решить проблему org.springframework.dao.InvalidDataAccessApiUsageException: Already registered a copy: SqmBasicValuedSimplePath(danila.mediasoft.test.warehouse.entities.Product(56225388223900).createAt)
при добавлении пагинации, без нее все работает хорошо.Не подскажите как можно решить эту проблему?

2024-05-01 10:12 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public ResponseEntity<List<ProductResponse>> searchByCriteria(@Validated @RequestBody List<Criteria> criteriaList) {
![image](https://github.com/Fulindak/warehouse/assets/76206833/358e6389-4b89-4b9f-8cc9-ef79fc30572e)

2024-05-01 10:15 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/ProductController.java
> +    public ResponseEntity<List<ProductResponse>> searchByCriteria(@Validated @RequestBody List<Criteria> criteriaList) {
скорее всего неверно сделан класс ProductSpecification

2024-05-01 10:19 UTC, GUR-ok requested changes

2024-05-01 10:19 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/search/ProductSpecification.java
> +    private List<Predicate> predicates;
```
    private List<Predicate> predicates;
    private PredicateStrategy strategy;
```
их не нужно хранить в объекте спецификации.. стратегии извлекаются динамически из критериев из списка criteriaList и для каждого критерия она своя.
Предикаты тоже нет смысла хранить. собирай на ходу. Пример:
    
```
    package com.crudshop.demo.service.search;

import com.crudshop.demo.entity.ProductEntity;
import com.crudshop.demo.service.search.criteria.SearchCriteria;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import lombok.RequiredArgsConstructor;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.lang.NonNull;

import java.util.List;

@RequiredArgsConstructor
@SuppressWarnings({"rawtypes", "unchecked"})
public class ProductSpecification implements Specification<ProductEntity> {

    private final List<SearchCriteria> criteriaList;

    @Override
    public Predicate toPredicate(
            @NonNull Root<ProductEntity> root,
            @NonNull CriteriaQuery<?> query,
            @NonNull CriteriaBuilder cb
    ) {
        final List<Predicate> predicates = criteriaList.stream().map(
                it -> {
                    switch (it.getOperation()) {
                        case EQUAL -> {
                            return it.getStrategy().getEqPattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        case GRATER_THAN_OR_EQ -> {
                            return it.getStrategy().getLeftLimitPattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        case LESS_THAN_OR_EQ -> {
                            return it.getStrategy().getRightLimitPattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        case LIKE -> {
                            return it.getStrategy().getLikePattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        default -> throw new IllegalStateException("Unexpected value: " + it.getOperation());
                    }
                }
        ).toList();

        return cb.and(predicates.toArray(new Predicate[0]));
    }
}
```

2024-05-01 11:11 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/search/ProductSpecification.java
> +    private List<Predicate> predicates;
Исправил по примеру и все заработало. Получается косяк был в том , что я хранил старые Predicate,в результате чего я не мог создавать новые, что и приводило к ошибке.

2024-05-04 10:07 UTC, GUR-ok approved these changes

2024-05-04 10:07 UTC, GUR-ok commented
Апрувнул. можно мержить со сквошем

2024-05-04 10:32 UTC, merged