Task3: create Currency service
Fulindak/warehouse pull request #7
Opened 2024-04-30 18:32 UTC by Fulindak

2024-05-01 10:37 UTC, GUR-ok requested changes

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/bean/HttpSessionBean.java
> +package danila.mediasoft.test.warehouse.bean;
странное название пакета. давай в другое место

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/bean/HttpSessionBean.java
> +public class HttpSessionBean {
Тебе название о чем-то говорит? Давай назовем CurrencyProvider

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/filter/CurrencyFilter.java
> +    public CurrencyFilter(HttpSessionBean httpSessionBean) {
@RequiredArgsConstructor взамен коснструктора

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/filter/CurrencyFilter.java
> +    public boolean isCurrencyInSession() {
для чего этот метод? он не нужен

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/ProductService.java
> +    public UUID createProduct(CreateProductDTO productDTO) {
не делай пожалуйста лишние изменения в мр по задаче. очень сложно смотреть ((( у кого-то 13 файлов по задаче меняется, у кого-то 30 (

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +                                     @Value("${currency-service.host}") String baseURL,
Давай больше не будем инжектить через value.
Создай класс для пропертей для rest взаимодействия
@ConfigurationProperties

2024-05-01 10:37 UTC, GUR-ok commented on src/main/resources/application.yaml
> +currency-service:
```
rest:
   currency-service:
```

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/WarehouseApplication.java
> +@EnableScheduling
EnableScheduling зачем добавился? он не дублируется?

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +                .retryWhen(Retry.backoff(2, Duration.ofSeconds(1)));
здесь нужно вызвать .block() в конце цепочки и работать уже не как с моно, а как с обычным объектом. У нас синхронно работает.

2024-05-01 10:37 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +public class CurrencyServiceClientImpl implements CurrencyServiceClient {
Задача класса клиента только ходить во второй сервис. Больше ничего. Нужно сделать еще одну обертку, которая по валюте отдает курс и она уже обращается сначала к клиенту, а потом читает из файла.
Называем класс ExchangeRateProvider
```
@Component
@Slf4j
@RequiredArgsConstructor
public class ExchangeRateProvider {

    private final CurrencyServiceClient currencyServiceClient ;
```    
Например имеет
1. удобный публичный метод, который позволит передать валюту, а в ответ получит курс. не нужно будет в продукт-сервисе много логики городить. Вызвал и все.
```
public BigDecimal getExchangeRate(Currency currency) {
    return Optional.ofNullable(getExchangeRateFromService(currency))
            .orElseGet(() -> getExchangeRateFromFile(currency));
}
```
2. Сделай два приватных метода. получение валюты из внешнего сервиса и получение из файла
 ```
 private @Nullable BigDecimal getExchangeRateFromService(Currency currency) {
    log.info("Получаем курс из второго сервиса или из кэша");
    return Optional.ofNullable(currencyServiceClient.getExchangeRate())
            .map(rate -> getExchangeRateByCurrency(rate, currency)).orElse(null);
}

private BigDecimal getExchangeRateFromFile(Currency currency) {
...
}

private BigDecimal getExchangeRateByCurrency(ExchangeRate exchangeRate, Currency currency) {
    return switch (currency) {
        case USD -> exchangeRate.getExchangeRateUSD();
        case CNY -> exchangeRate.getExchangeRateCNY();
        case EUR -> exchangeRate.getExchangeRateEUR();
        case RUB -> BigDecimal.ONE;
    };
}
```

2024-05-01 11:13 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/WarehouseApplication.java
> +@EnableScheduling
Нет, я еще не исправлял task1.
В develop  нет данной аннотации.

2024-05-01 11:17 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/filter/CurrencyFilter.java
> +    public boolean isCurrencyInSession() {
Забыл удалить, когда экспериментировал он проверял наличие Currency в классе, потом я сделал валюту по умолчанию и удалил его логику, а сам метод нет.

2024-05-01 11:40 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/filter/CurrencyFilter.java
> +            if (StringUtils.isNotBlank(currency)) {
Давай мб через опшнл?
```
Optional.ofNullable(currency)
           .map(CurrencyType::formValue)
           .ifPresent(currencyProvider::setCurrency);
```

2024-05-01 11:40 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/enums/CurrencyType.java
> +        throw new IllegalCurrencyTypeException("Unsupported currency type: " + value);
Давай мб нулл возвращать если не мапится?

2024-05-01 11:40 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/enums/CurrencyType.java
> +    public static CurrencyType formValue(String value) {
frommValue

2024-05-02 06:10 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/bean/HttpSessionBean.java
> +package danila.mediasoft.test.warehouse.bean;
перенес в пакет service/currency/provider

2024-05-02 06:11 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/ProductService.java
> +    public UUID createProduct(CreateProductDTO productDTO) {
Постараюсь больше так не делать

2024-05-02 06:11 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +                                     @Value("${currency-service.host}") String baseURL,
Исправил

2024-05-02 06:11 UTC, Fulindak commented on src/main/resources/application.yaml
> +currency-service:
Исправил

2024-05-02 06:12 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +                .retryWhen(Retry.backoff(2, Duration.ofSeconds(1)));
Исправил

2024-05-02 06:12 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +public class CurrencyServiceClientImpl implements CurrencyServiceClient {
Исправил

2024-05-02 06:57 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/enums/CurrencyType.java
> +        throw new IllegalCurrencyTypeException("Unsupported currency type: " + value);
Сделал, мне всегда казалось, что null не желательно возвращать

2024-05-02 06:58 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/enums/CurrencyType.java
> +    public static CurrencyType formValue(String value) {
Исправил

2024-05-02 06:58 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/filter/CurrencyFilter.java
> +            if (StringUtils.isNotBlank(currency)) {
Попробовал,не задумался использовать Optional таким образом.Пробовал только в репозитории их.

2024-05-02 06:59 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/filter/CurrencyFilter.java
> +    public CurrencyFilter(HttpSessionBean httpSessionBean) {
Исправил

2024-05-02 06:59 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/bean/HttpSessionBean.java
> +public class HttpSessionBean {
Исправил

2024-05-04 09:57 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/enums/CurrencyType.java
> +        throw new IllegalCurrencyTypeException("Unsupported currency type: " + value);
да, нулл возвращать плохо. но иногда можно. трай-кетч работает несколько дольше, т.к. мы будем там кетчить..

2024-05-04 09:59 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/WarehouseApplication.java
> +@EnableScheduling
а зачем он тут, если тут шедулеров нет?

2024-05-04 10:05 UTC, GUR-ok requested changes

2024-05-04 10:05 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +@ConditionalOnMissingBean(name = "currencyServiceMock")
убрать @ConditionalOnMissingBean а на моке поставить primary

2024-05-04 10:05 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +        // TODO Scheduling clear cache
а через конфиг не получится? убирай шедулер
```
spring:
  cache:
    cache-names: currencyRates
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s
```

2024-05-04 10:05 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceMock.java
> +@ConditionalOnProperty(prefix = "rest.currency-service", name = "mock", havingValue = "true")
тут primary. В случае активного мока у нас будет создавать оба бина. но инжектится будет тот, который primary.

2024-05-04 12:12 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/enums/CurrencyType.java
> +        throw new IllegalCurrencyTypeException("Unsupported currency type: " + value);
Понял, спасибо за разъяснение

2024-05-04 12:14 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/WarehouseApplication.java
> +@EnableScheduling
Для чистки кеша использовал шедулер, теперь в ней нет необходимости после того ,как сделал настройку жизни кеша внутри application.yaml

2024-05-04 12:26 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceMock.java
> +@ConditionalOnProperty(prefix = "rest.currency-service", name = "mock", havingValue = "true")
Понял, исправил

2024-05-04 12:49 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +        // TODO Scheduling clear cache
Исправил,  почитал про все варианты. Для нас, как я понял, expireAfterAccess вполне подходит.

2024-05-04 16:27 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceMock.java
> +@ConditionalOnProperty(prefix = "rest.currency-service", name = "mock", havingValue = "true")
matchifmissing false

2024-05-04 16:34 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/currency/CurrencyServiceClientImpl.java
> +@ConditionalOnMissingBean(name = "currencyServiceMock")
Исправил

2024-05-11 10:47 UTC, GUR-ok approved these changes
можно мержить со сквошем

2024-05-11 13:47 UTC, merged