Task4: Add Customer and Order
Fulindak/warehouse pull request #8
Opened 2024-05-09 08:53 UTC by Fulindak

![dbeaver_0Z7qOhResU](https://github.com/Fulindak/warehouse/assets/125123210/4fe80ef0-d6a9-4273-ba32-e881aa41e94b)

2024-05-11 11:09 UTC, GUR-ok requested changes

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/controllers/order/OrderController.java
> +    ResponseEntity<CreateOrderResponse> create(@Valid @RequestBody CreateOrderRequest orderRequest);
Не нужно заворачивать в ResponseEntity. RestController итак это делает

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    @JsonIgnore
Зачем @JsonIgnore ?

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    @Fetch(FetchMode.JOIN)
@Fetch(FetchMode.JOIN) решает n+1, но он делает FetchType = EAGER, т.е. теперь сущности выдергиваются всегда. нам это может быть не нужно. предлагаю сделать в репозитории метод c join-fetch|
```
    @Query("from OrderEntity o " +
            "left join fetch o.orderedProducts " +
            "where o.id = :orderId")
    Optional<OrderEntity> findByIdFetchOrderedProducts(UUID orderId);
 ```

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    private Customer customer;
За счет чего решается проблема n+1 с customer?
Мб поставим тут @Fetch(FetchMode.JOIN) ?

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/entities/OrderProduct.java
> +import jakarta.persistence.*;
импорты не схлопываем

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    public void addProduct(Set<OrderProduct> orderProducts) {
не знаю, обычно такие методы не делают.. я бы убрал.

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/order/OrderServiceImpl.java
> +        Order order = orderRepository.findById(id)
Зачем мы выдергиваем заказ? он еще и выдергивается с вложенной коллекцией

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/order/OrderServiceImpl.java
> +    public OrderDTO update(Set<OrderProductRequest> products, UUID id) {
здесь не нужно возвращать такую сложную дто. верни просто orderId

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/order/OrderServiceImpl.java
> +        Set<OrderProductDTO> products = orderProductService.getByOrderId(id);
orderProductService.getByOrderId(id) - выдергивает еще раз orderedProducts, а они же есть уже на Order order. Ордер не запрашивай.
 Сделай одним запросом через запрос проекции. пример
 ```
     @Query("""
                select new com.crudshop.demo.entity.projection.ProductProjection (
                    op.orderedProductKey.productId,
                    pe.description,
                    op.quantity,
                    op.price
                  )
                from OrderedProduct op
                  join ProductEntity pe on pe.id = op.orderedProductKey.productId
                  join OrderEntity oe on oe.id = op.orderedProductKey.orderId
                where op.orderedProductKey.orderId = :orderId
                and oe.customer.id = :customerId
            """)
    List<ProductProjection> getProjectionsByOrderIdAndCustomerId
            (UUID orderId, UUID customerId);
   ```

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +public class OrderProductServiceImpl implements OrderProductService {
Мб вообще уберем этот сервис? в OrderServiceImpl заинжектим private final OrderProductRepository orderProductRepository; ?

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +        return orderProductRequests.stream()
Собирай orderedProduct стримом в orderService.
в методе создания заказа логика должна быть такая:
1. Проверили кастомера, что он есть, если нет исключение
2. Находим все товары из запроса по айди одним селектом, делаем из этого хэшмапу productId -> productEntity
3. Создаем предварительно orderEntity, чтобы его сеттить в orderedProduct
4. По данным товаров из запроса проходимся стримом и собираем OrderedProduct, используя хэшмапу из шага два. Тут же проверяем количество и isAvailable
5. Сеттим в ордер эти товары. и сохраняемся

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +        Product product = productService.getProductAndTypes(orderProductRequest.id());
этот методы вызывается многократно, что плодит лишние селекты. селект можно сделать один для всех товаров в заказе. пример логики выше. Это главное замечание!

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +        Product product = productService.getProductAndTypes(orderProductRequest.id());
я бы логику этого метода делал в стриме в orderService, когда извлек нужные товары и их мапил в orderedProduct.

2024-05-11 11:09 UTC, GUR-ok commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +    public Set<OrderProduct> update(Set<OrderProductRequest> orderProductRequests, Order order) {
Передача вот так Order order через классы - не хорошо.. все, что здесь есть - это по сути приватные методы orderServiceImpl.

2024-05-15 11:33 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/controllers/order/OrderController.java
> +    ResponseEntity<CreateOrderResponse> create(@Valid @RequestBody CreateOrderRequest orderRequest);
Исправил.

2024-05-15 11:35 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    @JsonIgnore
Экспериментировал с аннотациями и передавал на прямую сущность в ответе , после чего забыл убрать

2024-05-15 11:40 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    @Fetch(FetchMode.JOIN)
Понял задумку, исправил

2024-05-15 11:41 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    private Customer customer;
Упустил этот момент , исправил

2024-05-15 11:45 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/entities/OrderProduct.java
> +import jakarta.persistence.*;
Поправил настройки idea, теперь не должны схлопываться

2024-05-15 11:46 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/entities/Order.java
> +    public void addProduct(Set<OrderProduct> orderProducts) {
ок, просто удобно  не получая коллекцию добавлять и удалять элементы . Исправил

2024-05-15 11:51 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/order/OrderServiceImpl.java
> +    public OrderDTO update(Set<OrderProductRequest> products, UUID id) {
Исправил

2024-05-15 12:18 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/order/OrderServiceImpl.java
> +        Set<OrderProductDTO> products = orderProductService.getByOrderId(id);
исправил

2024-05-15 12:24 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +public class OrderProductServiceImpl implements OrderProductService {
с учетом нижних комментариев , согласен , лучше убрать и добавить private  методы в OrderServiceImpl

2024-05-15 15:34 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +        return orderProductRequests.stream()
Изначально была похожая логика, потом я встал в ступор ,как из set вытащить нужно значение и решил, прикольно будет  вызывать все у каждой сущности ,но не подумал ,что может возникнуть проблемы с слишком частыми запросами. Исправил

2024-05-15 15:34 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +        Product product = productService.getProductAndTypes(orderProductRequest.id());
исправил

2024-05-15 15:34 UTC, Fulindak commented on src/main/java/danila/mediasoft/test/warehouse/services/orderproduct/OrderProductServiceImpl.java
> +    public Set<OrderProduct> update(Set<OrderProductRequest> orderProductRequests, Order order) {
исправил

2024-05-22 10:20 UTC, GUR-ok approved these changes
Давай подмержим со сквошем =)

2024-05-22 12:15 UTC, merged